menu:
  主页: /
  归档: /archives

logo: KUANG

more:
  Github: http://github.com/kuangch/
  关于我: http://kuangch.cn

about:
  title: kuangch
  link: http://kuangch.cn

disqus_shortname:

excerpt_num: 120

footer_info: © kuang 2016